version: "3.2"
services:


  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=db_user
      - MONGO_INITDB_ROOT_PASSWORD=db_password
      - MONGO_INITDB_DATABASE=predictions


  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
      
    environment:
     - RABBITMQ_DEFAULT_USER=my_user
     - RABBITMQ_DEFAULT_PASS=my_password


    networks:
        - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge
